version: "3.8"
services:
  database:
    image: postgres:14.5-alpine3.16
    env_file: ./docker/.env
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - ./database/data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    env_file: ./docker/.env 
    volumes:
      - .:/app/dev/etauliah
    container_name: etauliahph_app
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    command: sh -c "python manage.py collectstatic --noinput &&
                    gunicorn etauliahph.asgi:application --bind 0.0.0.0:8080  --workers 5 -k uvicorn.workers.UvicornWorker"

  web:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/app/dev/etauliah
    container_name: etauliahph_web
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    ports:
      - "80:80"
