FROM python:3.9-slim-bullseye
ENV PYTHONUNBUFFERED=1
WORKDIR /app/dev/etauliah
ENV DEBIAN_FRONTEND noninteractive
RUN pip install --upgrade pip
COPY ./requirements.txt /app/dev/etauliah/requirements.txt
RUN pip install -r requirements.txt
RUN apt-get -y clean
