# Generated by Django 3.2.8 on 2021-10-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cawangan', models.TextField(blank=True, default='TB', null=True, verbose_name='Cawangan')),
                ('nama', models.TextField(blank=True, default='TB', null=True, verbose_name='Nama')),
                ('noKP', models.TextField(blank=True, default='TB', null=True, verbose_name='noKP')),
                ('status', models.TextField(blank=True, default='TB', null=True, verbose_name='Status')),
                ('penyelia', models.TextField(blank=True, default='TB', null=True, verbose_name='Nama Penyelia')),
            ],
        ),
    ]
