# Generated by Django 3.2.8 on 2021-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauliah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='kelas',
            field=models.TextField(blank=True, default='TB', null=True, verbose_name='Kelas Latihan'),
        ),
    ]
